CREATE TABLE poi.City (
    CityID INT IDENTITY(1,1) PRIMARY KEY,
    CityName VARCHAR(255) NOT NULL,
    RegionID INT NOT NULL,
    CONSTRAINT UQ_City UNIQUE (CityName, RegionID),
    FOREIGN KEY (RegionID) REFERENCES poi.Region(RegionID),
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CreatedBy VARCHAR(100) NOT NULL DEFAULT SUSER_SNAME(),
    UpdatedOn DATETIME2 NULL,
    UpdatedBy VARCHAR(100) NULL
);
CREATE NONCLUSTERED INDEX IX_City_RegionID   ON poi.City (RegionID);
