--DROP TABLE poi.Country
CREATE TABLE poi.Country (
    CountryID INT IDENTITY(1,1) PRIMARY KEY,
    CountryCode VARCHAR(10) NOT NULL UNIQUE,
    CountryName VARCHAR(255) NOT NULL UNIQUE,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CreatedBy VARCHAR(100) NOT NULL DEFAULT SUSER_SNAME(),
    UpdatedOn DATETIME2 NULL,
    UpdatedBy VARCHAR(100) NULL
);
